name: ProcessMemoryDataFinder nuget CI
on:
  push:
    tags: 
      - process_v*
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: build
      run: dotnet build -c Release /p:Platform="Any CPU"
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'
    - name: Nuget Push
      run: nuget push ProcessMemoryDataFinder\bin\AnyCPU\Release\*.nupkg -Source https://api.nuget.org/v3/index.json
